# ç©ºç™½ã®Issueãƒ†ãƒ³ãƒ—ãƒ¬ãƒ¼ãƒˆã‚’ç„¡åŠ¹ã«ã™ã‚‹
blank_issues_enabled: false

# Issueãƒ†ãƒ³ãƒ—ãƒ¬ãƒ¼ãƒˆã®è¨­å®š
defaults:
  - template: "bug_report.yml"
    name: "ğŸ™‹â€â™‚ï¸ Report bugs"
    about: "The template for reporting bugs for this project."

  - template: "feature_request.yml"
    name: "ğŸ’¡ Request features"
    about: "The template for requesting new features for this project."

# ã‚³ãƒŸãƒ¥ãƒ‹ãƒ†ã‚£ã¸ã®èª˜å°
contact_links:
  - name: "ğŸ’¬ Community Discussions"
    url: "https://discord.com/invite/gEgjt9mbUU",
    about: "Join the discord community discussions for help and support."
  - name: "ğŸ“š Documentation"
    url: "https://ggg-alpha.github.io/docs/",
    about: "Find answers in the documentation."
